### ISSUE TITLE
Inheritance does not pull libraries into the scope

### ISSUE THREAD

**Issue by kleczkowski** [hyperledger-labs/solang#312]
### Description

Compiler does not pull libraries into the scope of subclasses.

### Repro

Consider following code: [amon_updated.zip](https://github.com/hyperledger-labs/solang/files/5516690/amon_updated.zip). During compilation driver panics:
```shell
$ solang amon_updated.sol
thread 'main' panicked at 'no entry found for key', src/codegen/expression.rs:1076:30
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::option::expect_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1213
   3: <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
   4: solang::codegen::expression::emit_function_call
   5: solang::codegen::expression::expression
   6: solang::codegen::expression::assign_single
   7: solang::codegen::expression::expression
   8: solang::codegen::statements::statement
   9: solang::codegen::cfg::generate_cfg
  10: solang::codegen::codegen
  11: solang::process_filename
  12: solang::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Adding some dummy operations to `AMNToken` that involves `SafeMath` library, e.g.
```solidity
contract AMNToken is StandardToken {

  string  public constant name = "Amon";
  string  public constant symbol = "AMN";
  uint8   public constant decimals = 18;
  uint256 public constant INITIAL_SUPPLY = (1666666667) * (uint256(10) ** decimals);

  /**
    *@dev Constructor that set the token initial parameters
    */
  constructor()
  {
    uint256 totalSupply_ = INITIAL_SUPPLY.add(uint256(0)); // dummy op here
    balances[msg.sender] = totalSupply_;
  }

}
```
allows to compile the file.

### Observation

I've noticed that libraries are loaded on-demand, omitting the fact that it could break inheritance constraints. Function `import_library` should be invoked each time, when contract is a subtype of another despite that library is used or not.

**Comment by seanyoung** [comment]
Thanks for the bug report and detailed analysis. I think you are totally right, I am working on a fix now.
