### ISSUE TITLE
Problem with Language Server

### ISSUE THREAD

**Issue by ChristianChiarulli** [hyperledger-labs/solang#553]
Using command: 

```
            cmd = { path.concat { root_dir, "solang" }, "--language-server", "--target", "ewasm" },
```

Returns this error:

```
[ERROR][2021-11-09 23:04:35] .../vim/lsp/rpc.lua:462	"rpc"	"/home/chris/.local/share/nvim/lsp_servers/solang/solang"	"stderr"	"thread 'main' panicked at 'not implemented', src/emit/ewasm.rs:834:9\nstack backtrace:\n"
[ERROR][2021-11-09 23:04:35] .../vim/lsp/rpc.lua:462	"rpc"	"/home/chris/.local/share/nvim/lsp_servers/solang/solang"	"stderr"	"   0: rust_begin_unwind\n             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5\n   1: core::panicking::panic_fmt\n             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14\n   2: core::panicking::panic\n             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5\n   3: solang::emit::TargetRuntime::storage_load_slot\n   4: solang::emit::TargetRuntime::emit_cfg\n   5: solang::emit::TargetRuntime::emit_functions\n   6: solang::emit::ewasm::EwasmTarget::build\n   7: solang::codegen::codegen\n   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n"
[ERROR][2021-11-09 23:04:35] .../vim/lsp/rpc.lua:462	"rpc"	"/home/chris/.local/share/nvim/lsp_servers/solang/solang"	"stderr"	"  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  11: <futures_util::stream::stream::fuse::Fuse<S> as futures_core::stream::Stream>::poll_next\n  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  13: solang::main\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"
```

**Comment by seanyoung** [comment]
The problem is that ewasm does not have the implementation for string in contract storage.

What would you like to use the ewasm target for?
