### ISSUE TITLE
'not implemented' error when trying to compile to `ewasm`

### ISSUE THREAD

**Issue by cassc** [hyperledger-labs/solang#689]
When trying to compile to the following contract using `solang --target  ewasm test.sol` 

```solidity
contract JamCoin { 
    /* Public variables of the token */
    string public name;
    string public symbol;
    uint8 public decimals;
    
    /* This creates an array with all balances */
    mapping (address => uint256) public balanceOf;
    
    /* This generates a public event on the blockchain that will notify clients */
    event Transfer(address indexed from, address indexed to, uint256 value);
    
    /* Initializes contract with initial supply tokens to the creator of the contract */
    constructor() {
        /* Unless you add other functions these variables will never change */
        balanceOf[msg.sender] = 10000;
        name = "Jam Coin";     
        symbol = "5ea56e7bfd92b168fc18e421da0088bf";
        decimals = 2;
    }

    /* Send coins */
    function transfer(address _to, uint256 _value) public {
        /* if the sender doenst have enough balance then stop */
        require (balanceOf[msg.sender] >= _value) ;
        require (balanceOf[_to] + _value >= balanceOf[_to]) ;
        
        /* Add and subtract new balances */
        balanceOf[msg.sender] -= _value;
        balanceOf[_to] += _value;
        
        /* Notifiy anyone listening that this transfer took place */
        emit Transfer(msg.sender, _to, _value);
    }
}
``` 

I got this error, 

```
thread 'main' panicked at 'not implemented', src/emit/ewasm.rs:834:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::panic
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
   3: <solang::emit::ewasm::EwasmTarget as solang::emit::TargetRuntime>::get_storage_string
```

**Comment by seanyoung** [comment]
dup #166
