### ISSUE TITLE
Inkwell crashes when building contract

### ISSUE THREAD

**Issue by LucasSte** [hyperledger-labs/solang#867]
The following contract crashes Inkwell when compiling for Solana and Substrate

```solidity
contract DeleteTest {

struct rest {
    uint a;
    uint b;
}

struct tt {
    string a;
    address addr;
    rest r_st;
    int[4] vec;
}

    function getVec() public returns (int[] memory, int) {
         rest ss = rest({a: 1, b: 2});
        tt testing = tt({a: "tea", addr: msg.sender, r_st: ss, vec: [1, 2, 3, 4]});
        int[] ret = testing.vec;
        return (ret, ret[2]);
    }

}
```

**Comment by LucasSte** [comment]
I'm getting this error:

```
thread 'main' panicked at 'Found ArrayType(ArrayType { array_type: Type { address: 0x7ff009034180, llvm_type: "[4 x i256]" } }) but expected the StructType variant', /Users/lucas/.cargo/registry/src/github.com-1ecc6299db9ec823/inkwell-0.1.0-beta.4/src/types/enums.rs:272:13
```

**Comment by davidleng0x0** [comment]
I got this error too.

    thread 'main' panicked at 'Found ArrayType(ArrayType { array_type: Type { address: 0x1dff8cddc90, llvm_type: "[32 x i8]" } }) but expected the IntType variant', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\inkwell-0.1.0-beta.4\src\types\enums.rs:390:13

**Comment by LucasSte** [comment]
This is the smallest failing contract:

```solidity
contract DeleteTest {

        struct tt {
            int[4] vec;
        }

    function getVec() public returns (int) {
        tt memory testing = tt({vec: [int(1), 2, 3, 4]});
        int[] memory ret = testing.vec;
        return ret[2];
    }

}
```
We should not allow the conversion between `int[]` and `int[4]`.
